### PR TITLE
Update to latest groovy and cucumber jvm

### PR DESCRIPTION
**Pull request by lsiu**
### 🤔 What's changed?

Upgrade to the latest `groovy` version 4.0.11 and `cucumber-core` version 7.11.2

### ⚡️ What's your motivation? 

I would like to use cucumber-groovy-jvm with the latest cucumber-core

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### ♻️ Anything particular you want feedback on?

* I don't know the historry to running the maven ant `groovy-cli-test`, I replaced it with the `org.junit.platform.console.ConsoleLauncher

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Review by mpkorstanje — COMMENTED** [review]
Heya, looked pretty good. I pushed some changes to help out.

Specifically:
 * Upgrading to Surefire v3 so we can use JUnit 5.
 * Using Bills of Material to keep all the dependencies aligned (and remove all the explicit version numbers everywhere)
 * Replacing JUnit 4 with JUnit 5.

Don't forget to add an entry to the `CHANGELOG.md`.

> I don't know the historry to running the maven ant groovy-cli-test, I replaced it with the `org.junit.platform.console.ConsoleLauncher

Interesting question.

I get the impression that the `groovy-cli-test` is testing the `cucumber-groovy-shaded.jar` that is produced when building this project. It seems to be a way to run Cucumber Groovy in a standalone fashion. 

If you think that currently there is no reason to provide a shaded jar, please do feel free to remove the code that creates the shaded jar along with the test for it. Since this project currently doesn't have a maintainer (#27) and I don't use Groovy on regular basis I'll defer to your judgement on this.

**Comment by lsiu** [comment]
I put the `groovy-cli-test` back it. It just wraps the `cli` mechanism provided by [cucumber-core](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/cli/Main.java). Doesn't look like too much work to support it for now.

**Comment by aslakhellesoy** [comment]
Hi @lsiu,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by lsiu** [comment]
@mpkorstanje , I will do what I can. 
To be honest, I started with cucumber-jvm-groovy in my previous job. Finally, got around to introduce this in my new job, but found out `cucumber-jvm-groovy` is no longer maintained. Tried `cucumber-jvm-java8` and learned it is getting deprecated, so I went with `cucumber-jvm-java`.  IMHO, the duplicate step text in annotation and method name is still not idea, so I am trying to give `cucumber-jvm-groovy` a kick.

**Pull request merged**
