### PR TITLE
Upgrade jackson version

### PR DESCRIPTION
**Pull request by mlvandijk**
Reason: https://github.com/FasterXML/jackson-databind/issues/2186

(Sorry, I meant to do this in a PR)

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Might worth noting that Jackson dependency should be `test` scoped.

**Comment by mpkorstanje** [comment]
Looks like the build fails because the `maven-antrun-plugin` does not use the test dependency scope.

**Comment by mlvandijk** [comment]
I'm getting the following:
```
     [echo] Running groovy tests via the CLI...
     [java] Caught: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
     [java] java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
  ```
so I guess it does need Jackson outside the test scope?

**Comment by mlvandijk** [comment]
Or is running the tests outside the test scope?

**Comment by mlvandijk** [comment]
Removing test scope should fix the build

**Comment by mpkorstanje** [comment]
That fixes the build. But the project shouldn't have a dependency on Jackson when it is only used for tests. To `test` scope was correct. We do have to make sure that the `antrun-plugin` can access them too. To do this you can provide a `classpathref` to the [Java Ant task](https://ant.apache.org/manual/Tasks/java.html).

In this case `classpathref="maven.test.classpath"` should do the trick.

**Comment by mlvandijk** [comment]
Not familiar with this plugin and wasn't able to figure out where to set that `classpathref` last night. If you know how to do it, please go ahead. It is failing during the `integration-test` phase atm.

**Pull request merged**
